### ISSUE TITLE
Amulet skips local charms when uncommitted bzr changes are present

### ISSUE THREAD

**Issue by chuckbutler** [juju/amulet#55]
When deploying a charm in bundle format from a dirty directory - it skips loading the local charm and instead resorts to using the store charm. A known work-around is to commit the changes pre-emptively before executing the test.

#### Conditions that exhibited the behavior:

The following bundle yaml was loaded in an amulet test for hdp-hive

```
  "compute-node":
      charm: "hdp-hadoop"
      num_units: 2
      annotations:
        "gui-x": "768"
        "gui-y": "591.0585428804295"
    mysql:
      charm: "cs:trusty/mysql"
      num_units: 1
      options:
        "binlog-format": ROW
      annotations:
        "gui-x": "1102.9983551210835"
        "gui-y": "591.0585428804295"
    hdp-hive:
      charm: "hdp-hive"
      num_units: 1
      annotations:
        "gui-x": "1105.4991775605417"
        "gui-y": "284.9414571195705"
    "yarn-hdfs-master":
      charm: "hdp-hadoop"
      num_units: 1
      annotations:
        "gui-x": "769.0016448789165"
        "gui-y": "285.0585428804295"
  relations:
    - - "hdp-hive:namenode"
      - "yarn-hdfs-master:namenode"
    - - "yarn-hdfs-master:namenode"
      - "compute-node:datanode"
    - - "hdp-hive:resourcemanager"
      - "yarn-hdfs-master:resourcemanager"
    - - "yarn-hdfs-master:resourcemanager"
      - "compute-node:nodemanager"
    - - "compute-node:hadoop-nodes"
      - "hdp-hive:hadoop-nodes"
    - - "hdp-hive:db"
      - "mysql:db"
  series: trusty
```

Bundletester was executed from the charm directory:

` $ bundletester -F -l DEBUG -v -e hpcloud`

Output snippet from juju status:

```
  hdp-hive:
    charm: cs:trusty/hdp-hive-2
```

current bzr status in directory: 

```
removed:
  files/data/
  files/data/elasticsearch-hadoop-2.0.0.zip
  hooks/elasticsearch-relation-joined@
  hooks/hadoop-nodes-relation-changed@
added:
  hooks/elk-relation-joined@
modified:
  README.md
  hooks/hdp-hive-common.py
  icon.svg
  metadata.yaml
  tests/01-deploy-hive-cluster
  tests/hive-hadoop-sql-cluster.yaml
unknown:
  tests/trusty/
```
